services:
    caddy:
        image: ghcr.io/nyukeit/caddy-cloudflare:latest
        container_name: caddy
        restart: unless-stopped
        environment:
            - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ${CADDYFILE}:/etc/caddy/Caddyfile
            - ${DATA_DIR}:/data
            - ${CONFIG_DIR}:/config
        networks:
            - proxy

networks:
    proxy:
        external: true
