services:
    vaultwarden:
        image: vaultwarden/server:latest
        container_name: vaultwarden
        # Mount Security hardening variables
        env_file: .env
        environment:
            - DOMAIN=${VW_DOMAIN}
        volumes:
            - ${VW_DATA_DIR}:/data/
        restart: unless-stopped
        networks:
            - proxy

networks:
    proxy:
        external: true
