services:
    arcane:
        image: ghcr.io/getarcaneapp/arcane:latest
        container_name: arcane
        environment:
            - ENCRYPTION_KEY=${ENCRYPTION_KEY}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${ARCANE_DATA_DIR}:/app/data

        # Add a compose projects folder if managing local projects (optional)
        #   - ${COMPOSE_PROJECTS_DIR}:${COMPOSE_PROJECTS_DIR}
        restart: unless-stopped
        networks:
            - proxy

networks:
    proxy:
        external: true
