services:
    tailscale:
        image: tailscale/tailscale:latest
        container_name: tailscale
        hostname: homeserver
        environment:
            - TS_STATE_DIR=/var/lib/tailscale
            - TS_AUTHKEY=${TS_AUTHKEY}
        volumes:
            - ${TS_STATE_DIR}:/var/lib/tailscale
            - ${TS_CERTS_DIR}:/var/lib/tailscale/certs
            - /dev/net/tun:/dev/net/tun
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        restart: unless-stopped
        network_mode: host
